### ISSUE TITLE
implements RPC to query proposal status

### ISSUE THREAD

**Issue by kysee** [rigochain/rigo-go#10]
현재 freezing 된 proposal 에 대한 조회 방법이 없음.
추가적으로 freezing 된 proposal 을 조회할 수 있도록 RPC 개선

**Comment by kylekwon-rigochain** [comment]
test code 작성중   
sdk 관련 로직 처리후 계속 진행

**Comment by kylekwon-rigochain** [comment]
하나의 RPC 로 구현하고, 
응답에 리턴되는 proposal 의 상태 ("voting", "frozen") 을 표히사는 필드 추가.

**Comment by EokgiLee** [comment]
develop branch에 pull request 완료
