### ISSUE TITLE
Update TrxPayloadProposal

### ISSUE THREAD

**Issue by kyle-themedium** [rigochain/rigo-go#113]
#112 에 의하여 변경된 governance proposal 의 적용 시점을 결정할 새로운 필드가 필요.  

```diff
type TrxPayloadProposal struct {
	Message            string
	StartVotingHeight  int64
	VotingPeriodBlocks int64
+       LazyApplingPeriodBlocks int64
	OptType            int32
	Options            [][]byte
}
```

- `StartVotingHeight` ~ `StartVotingHeight  + VotingPeriodBlocks` : 투표기간
- `StartVotingHeight  + VotingPeriodBlocks + LazyApplingPeriodBlocks` 적용 시점

**Comment by kylekwon-rigochain** [comment]
#112  으로 구현 완료
