### ISSUE TITLE
rigo command line tool 기능 목록 정의

### ISSUE THREAD

**Issue by kyle-themedium** [rigochain/rigo-go#115]
rigo rpc 를 이용하여 rigo network 와 상호 작용시 
월렛 어플리케이션이 아닌 command line 으로도 가능한 tool 구현

ex)
```bash
$ rigocmd tx --type transfer --from ... --to .... --amt ....
...

$ rigocmd tofons 1
1000000000000000000

...
```

 
- 구현한 기능(명령어) 정의
- 파라메터 정의 
- 출력 포멧 정의

**Comment by kyle-rigochain** [comment]
[RIGO Command Line Tool](https://github.com/rigochain/rigo-go/wiki/RIGO-Command-Line-Tool)
