### ISSUE TITLE
reward ledger 가 변경됨에 따라 1초마다 block 생성 문제

### ISSUE THREAD

**Issue by kyle-themedium** [rigochain/rigo-go#116]
블록 마다 보상이 주어지기 때문에, reward ledger 가 계속 변경됨.
이로 인해 `--consensus.create_empty_blocks_interval` 옵션과 상관 없이
1초 마다 블록 생성이 강제되는 문제.

**Comment by kylekwon-rigochain** [comment]
rewardLedger 의 hash 를 n blocks 마다 반영하도록 하는 방법...
