### ISSUE TITLE
Validate proposal option

### ISSUE THREAD

**Issue by kyle-themedium** [rigochain/rigo-go#121]
Proposal(governance params) 를 적용할 때,
Option 의 내용을 Unmarshal 하면서 에러 발생 함.

*잘못된 option*
아래 옵션에서 **""}** 부분이 잘못됨. 
```json
{"version": "2","rewardPerPower": "1085489599","lazyApplyingBlocks":"600""}
```

TrxPayloadProposal 에 대한 ValidateTrx 에서
Option 내용에 대한 정합성 체크 필요.

**Comment by EokgiLee** [comment]
1.  변경 내용 : ValidateTrx 에서 TRX_PROPOSAL 일 경우에 check 로직 추가
2. 세부 사항 : payload의 option을 unmarshal 수행하여 정상적으로 통과되는지 확인
