### ISSUE TITLE
broadcast_tx로 unstaking을 보냈을때 처리 실패했는데 응답값이 0 으로 리턴

### ISSUE THREAD

**Issue by ryanpark-themedium** [rigochain/rigo-go#128]

**Comment by kyle-themedium** [comment]
broadcast_tx_async/sync/commit 중 어느 것인가요?
@ryanpark-themedium

**Comment by kyle-themedium** [comment]
`broadcast_tx_async` 또는 `broadcast_tx_sync` 호출 결과 코드가 0 (success) 이라 할지라도,  
이것이 블록체인에 해당 tx 가 **success 되어 기록(commit) 되었음을 의미하지 않음.**

특히 `broadcast_tx_sync` 의 경우, 리턴 값의 `code` 팔드가 0 일때,  
이는 `CheckTx` 의 성공을 의미하며 `DeliverTx` 시 성공을 보장하지 않음.

따라서, 

`broadcast_tx_async` 또는 `broadcast_tx_sync`  로 Tx 을 제출하였을 때는, 
해당 Tx 의 이벤트를 수신하거나, 트랜잭션 조회를 통해 최종적으로 성공 여부를 판단해야 함.  
또는 `broadcast_tx_commit` 를 사용하여, 
`CheckTx` 의 응답과, `DeliverTx` 의 응답 모두가 0 (success) 임을 확인해야 함.

**Comment by ryanpark-themedium** [comment]
broadcast_tx_sync 로 보내서 생긴 문제

broadcast_tx_sync 를 broadcast_tx_commit 으로 변경하고 CheckTx, DeliverTx의 code값이 모두 0일때 성공으로 수정

이슈 수정 완료 : https://github.com/rigochain/byffin-wallet/issues/44
