### ISSUE TITLE
Add meta data of validator to `TrxPayloadStaking`

### ISSUE THREAD

**Issue by kysee** [rigochain/rigo-go#31]
스테이킹을 하는 계정에 대한 메타정보 추가.
- Name
- Description (Introduce myself)
- URL
- E-Mail
- ...

**Comment by kyle-themedium** [comment]
`Account` 에 `DocURL` 필드를 추가하고, 
이 필드의 url 이 account owner 에 대한 정보를 담은 데이터를 가리키도록 함.
