### ISSUE TITLE
Integrate EVM

### ISSUE THREAD

**Issue by kysee** [rigochain/rigo-go#36]

**Comment by kyle-themedium** [comment]
`eth_call` 에 대응되는 `vm_call` RPC 추가함.
`vm_call` 의 경우, db(ledger) update 가 발생해서는 안된다. 
그런데 ... evm 에서 SubBalance 등 db update 가 발행하는 콜백이 호출된다...

`vm_call` 을 처리하는 경우, db 복사본을 가지고 이를 수행해야 한다.
`eth_call` 의 경우 그리 한다...  (internal/ethapi/api.go 의 `DoCall(...)` 참조)

**Comment by kyle-themedium** [comment]
evm 에서 코드 실행중 balance 또는 nonce 변경과 같이 db에 state 저장이 필요할 때 
`vm.StateDB` 의 함수가 호출된다.
그런데 이 함수내에서는 현재 실행 중인 tx 가 Rigo 의 `CheckTx` 에서 인지, `DeliverTx` 인지 구분할 수 없다.
따라서 `acctHandler` 호출시 `exec` 필드 값 (`true` or `false`) 정할 수 없다.
