### ISSUE TITLE
HEACHI LABS Report - 3

### ISSUE THREAD

**Issue by kyle-themedium** [rigochain/rigo-go#41]
발견된 이슈 전달드립니다.Block 당 과도한 GasLimit이 설정되어있고 EVM에서 opcode가 실행된만큼 gas를 sender의 balance에서 차감하는것이 아니라 sender가 gas를 내고싶은만큼 낼 수 있습니다.이로 인해서 과도한 loop가 돌아가는 transaction을 계속 쏠 경우에 적은 비용으로 block 생성을 방해할 수 있는 DOS가 있다고 판단됩니다.

```
func evmBlockContext(sender common.Address, bn int64, tm int64) vm.BlockContext {
    return vm.BlockContext{
        CanTransfer: CanTransfer,
        Transfer:    Transfer,
        GetHash:     GetHash,
        Coinbase:    sender,
        BlockNumber: big.NewInt(bn),
        Time:        big.NewInt(tm),
        Difficulty:  big.NewInt(1),
        BaseFee:     big.NewInt(0),
        GasLimit:    gasLimit * 10_000, //10_000_000_000_000_000_000,
    }
}
...
func (ctrler *EVMCtrler) ExecuteTrx(ctx *ctrlertypes.TrxContext) xerrors.XError {
    ...
    ret, xerr := ctrler.execVM(
        ctx.Tx.From,
ctx.Tx.To,
        ctx.Tx.Nonce,
        ctx.Tx.Amount,
        ctx.Tx.Payload.(*ctrlertypes.TrxPayloadContract).Data,
        ctx.Height,
        ctx.BlockTime,
    )
    ...
    ctx.RetData = ret.ReturnData

    // 문제가 되는 코드입니다
    ctx.GasUsed = ctx.Tx.Gas //new(uint256.Int).Add(ctx.GasUsed, uint256.NewInt(ret.UsedGas))
    ctrler.stateDBWrapper.SubBalance(ctx.Tx.From.Array20(), ctx.GasUsed.ToBig())

    return nil
}

```

해결책으로는 ctx.GasUsed에 ctx.Tx.Gas가 아닌 주석에 있는대로 new([[uint256.Int](http://uint256.int/)](http://uint256.int/)).Add(ctx.GasUsed, uint256.NewInt(ret.UsedGas))로 설정하는 것을 권장드리며 GasLimit도 저것보다 작은 25000000으로 설정하는것을 권장드립니다. (25000000은 cosmos-sdk/tendermint 기반의 크로노스 체인의 값을 참조했습니다)

**Comment by kalos-security** [comment]
이것과 관련한 추가 이슈 말씀드립니다.
ctx.GasUsed에 EVM에서 사용한 가스가 들어가긴하나 이를 Transaction Sender의 잔고에서 실질적으로 차감하는 코드가 존재하지않습니다.
이 코드를 추가하는것을 권장드립니다.

**Comment by kyle-themedium** [comment]
sender 의 잔고에서 실질적으로 차감하는 것은,
EVM 내에서 StateDB 의 SubBalance 를 통해 EVM db 에 반영하고, 
이에 대하여 EVMCtrler.ExecuteTrx 가 종료될때 실행되는 `ApplyTo()` 에서 rigo db 로 반영 됩니다.

**Comment by kalos-security** [comment]
https://haechilabs.slack.com/archives/C057LDCTF1P/p1685551825975159

**Comment by kalos-security** [comment]
확인했습니다.
