### ISSUE TITLE
[RIGO-12] Incomplete Update of Staking Object with GovRule Changes through Voting

### ISSUE THREAD

**Issue by kalos-security** [rigochain/rigo-go#52]
# [RIGO-12] Incomplete Update of Staking Object with GovRule Changes through Voting

## Impact

Some users may have inappropriate Voting Power and BlockReward.

## Description

```golang
func (ctrler *GovCtrler) applyProposals(height int64) xerrors.XError {
	xerr := ctrler.frozenLedger.IterateReadAllItems(func(prop *proposal.GovProposal) xerrors.XError {
		if prop.ApplyingHeight <= height {
			...
			if prop.MajorOption != nil {
				switch prop.OptType {
				case proposal.PROPOSAL_GOVRULE:
					newGovRule := &ctrlertypes.GovRule{}
					if err := json.Unmarshal(prop.MajorOption.Option(), newGovRule); err != nil {
						return xerrors.From(err)
					}
					if xerr := ctrler.ruleLedger.SetFinality(newGovRule); xerr != nil {
						return xerr
					}
					ctrler.newGovRule = newGovRule
				default:
					key := prop.Key()
					ctrler.logger.Debug("Apply proposal", "key(txHash)", abytes.HexBytes(key[:]), "type", prop.OptType)
				}
			} else {
				ctrler.logger.Error("Apply proposal", "error", "major option is nil")
			}
		}
		return nil
	})

	return xerr
}
```

```golang
func (ctrler *GovCtrler) Commit() ([]byte, int64, xerrors.XError) {
	...
	if ctrler.newGovRule != nil {
		ctrler.GovRule = *ctrler.newGovRule
		ctrler.newGovRule = nil
		....
	}
        ...
}
```

The above code successfully updates the new GovRule.
However, it needs to update the corresponding values of the existing Stake Object, resulting in consistency between the GovRule and the associated Stake Object.

## Recommendations

When the GovRule is updated, it is recommended to update the power and BlockRewardUnit based on the amount of the existing Stake Object.

**Comment by kyle-themedium** [comment]
* `BlockRewardUnit` 는 기록된 값이 아닌 runtime 시에 계산하여 사용하도록 수정.
* `AmoutPerPower` 를 governance parameters(rule) 에서 제거 하여, 더이상 proposal 에 의해 변경되지 않도록 수정.  
이는 단순 비율로서 이 값이 변하더라도 모두에게 동일하게 적용되는바    
validator 선택 이나 voting 시 power 순위에 변경을 유발하지 않음.  
보상률 조정 문제는 `RewardPerPower` 로 충분히 조정 가능함.
따라서 반드시 governance parameters 이어야 할 필요가 없는 것으로 판단하여 governance parameters 에서 제거함.

**Comment by kalos-security** [comment]
확인했습니다.
