### ISSUE TITLE
[RIGO-17] incorrect txhash

### ISSUE THREAD

**Issue by kalos-security** [rigochain/rigo-go#57]
# [Rigo-17] incorrect txhash

## Impact

The transaction hash value expected by the user and the transaction hash value used in rigo may differ.

## Description

Currently, an incorrect value is being used for transaction hashes in Rigo. This discrepancy arises because the transaction hashes are generated using data that includes the transaction signature information.

Including the signature information in the transaction hash is illogical since the transaction signature is derived from the transaction hash. As a result, users may encounter situations where the transaction hash they expect does not match the transaction hash used within Rigo.

```go
// rigo-go/ctrlers/types/trx_ctx.go
func NewTrxContext(txbz []byte, height, btime int64, exec bool, cbfns ...NewTrxContextCb) (*TrxContext, xerrors.XError) {
	tx := &Trx{}
	if xerr := tx.Decode(txbz); xerr != nil {
		return nil, xerr
	} else if tx.Amount.Sign() < 0 {
		return nil, xerrors.ErrNegAmount
	} else if tx.Gas.Sign() < 0 {
		return nil, xerrors.ErrNegFee
	}

	txctx := &TrxContext{
		Tx:        tx,
		TxHash:    types.Tx(txbz).Hash(),
```

## Recommendations

When generating transaction hashes, ensure that the signature information is excluded, using only the data without the transaction signature to create the transaction hash.

**Comment by kyle-themedium** [comment]
텐더민트 엔진에서 signature 를 포함한 tx 데이터를 가지고 hash 를 구하여 사용함.
Rigo 는 텐데민트의 tx hash 계산에 의존성을 갖기에 현재 상태를 유지하여야 함.
