### ISSUE TITLE
[RIGO-20] Insufficient Token Distribution Explanation and Misalignment with Block Rewards-Based Distribution Design

### ISSUE THREAD

**Issue by kalos-security** [rigochain/rigo-go#60]
# [Rigo-20] Insufficient Token Distribution Explanation and Misalignment with Block Rewards-Based Distribution Design

## Impact

Token circulation deviates from the team's planned token distribution outlined in the documentation.

## Description

Currently, the distribution plan of the project does not include information about the native token generated as block rewards.

Additionally, there are no limitations in place for the block rewards issued. Validators' block rewards increase proportionally to the number of native tokens staked, but without any restrictions on the block rewards, there is a possibility that the token circulation may deviate from the team's planned distribution model or tokenomics.

## Recommendations

- Define and document the native token information related to block rewards in the token economic docs, including details such as issuance rate, allocation mechanism, and distribution plan.
- Implement limitations on block rewards to align with the intended token distribution plan and prevent potential discrepancies.

**Comment by kysee** [comment]
텐더민트에서는 tx 가 없을 경우, 
설정된 블록 생성 주기(create_empty_blocks_interval)에 따라 빈 블록(empty block) 을 생성함.
반면에 tx 가 발생하면 이 주기를 기다리지 않고, 바로 블록 생성하며 이때 블록 생성 시간은 최소 1s 가됨.

`create_empty_blocks_interval` 를 `3s) 로 잡았을 때, 
1년동안 생성될 수 있는 
* 최소 블록수 = 10,512,000 개 (1년동안 1개의 tx 도 발생하지 않았을 경우)
* 최대 블록수 = 31,536,000 개 (모든 블록에 tx 가 존재할 경우)

스테이킹된 지분 1RIGO (10^18 wei) 당 4,756,468,797 wei 를 보상으로 지급할 경우, 
* 최소 블록 보상분/1년,1RIGO = 4,756,468,797 * 10,512,000 = 49,999,999,994,064,000 ~= 0.05 RIGO (5% of 1RIGO)
* 최대 블록 보상분/1년,1RIGO = 4,756,468,797 * 31,536,000 = 149,999,999,982,192,000 ~= 0.15 RIGO (15% of 1RIGO)

따라서 RIGO 의 추가 발행 비율은, 스테이킹된 지분 총량의 5% ~ 15% 범위로 제한됨.

**Comment by kalos-security** [comment]
토큰 이코노믹("리고(RIGO) 토큰 이코노믹 230531.pdf") 정보가 업데이트 된 것을 확인했습니다.
