### ISSUE TITLE
Add events of XXXCtrlers

### ISSUE THREAD

**Issue by kysee** [rigochain/rigo-go#63]
In order for an external application to monitor what is happening on the RIGO Network, what has happened on the network must be communicated in the form of `Event` to the Consensus Engine and ultimately to the external application.

RIGO should generate the following events:

for all tx
- `tx.hash`
- `tx.height`
- [x] `tx.type`
- [x] `tx.sender`
- [x] `tx.receiver`
- [x] `tx.addrpair`

for txs related to evm (contract)
- [x] `vm.topic_0`
- [x] `vm.topic_1`
- [x] `vm.topic_2`
- [x] `vm.topic_3`
- [x] `vm.data`

for block
- `block.height`
- [x] `punishment.byzantine`
- [x] `punishment.height`
- [x] `punishment.type`
- [x] `punishment.slashed`
- [x] `proposal.frozen`
- [x] `proposal.removed`
- [x] `proposal.applied`
- ~~[ ] `reward.`~~
- ~~[ ] `unfreezing.stake`~~

**Comment by kyle-themedium** [comment]
Add 
- proposal.frozen
- proposal.removed
- proposal.applied
